POST http://localhost:4300/circles/
Content-Type: application/json
AuthID: 59f375c40f8507376c6b63e3

{
  "name": "DEV circle",
  "handle": "dev",
  "description": "DEV 2018"
}
###
POST http://localhost:4300/users
Content-Type: application/json

{
  "email_address": "segebee@gmail.com",
  "username": "segebee",
  "first_name": "segebee",
  "password": "segebee"
}

###
GET http://localhost:4300/circles/all
authid: 59f1782b568e4c18cc22a695
###
GET http://localhost:4300/polls/all
authid: 59f375c40f8507376c6b63e3
###
GET http://localhost:4300/users
###

POST http://localhost:4300/polls/
Content-Type: application/json
AuthID: 59f375c40f8507376c6b63e3

{
  "question": "Who is the best JS framwork",
  "comment": "Let's know what it is",
  "circle": "59f37eb657ba4e1dec3e13c0",
  "options": [
    {
      "option": "Angular",
      "votes":0
    },
    {
      "option": "React",
      "votes":0
    },
    {
      "option": "Vue",
      "votes":0
    },
    {
      "option": "Ember",
      "votes":0
    }
  ]
}