GET http://localhost:4300/circles/all
Content-Type: application/json
AuthID: 5a3618879662a518502932c0
###
GET http://localhost:4300/users/
Content-Type: application/json
AuthID: 5a3618879662a518502932c0
###
GET http://localhost:4300/polls/all
Content-Type: application/json
AuthID: 5a3618879662a518502932c0



###
DELETE http://localhost:4300/users/all
AuthID: 5a3618879662a518502932c0
###
POST http://localhost:4300/circles/
Content-Type: application/json
AuthID: 5a3618879662a518502932c0

{
  "name": "Beulah Slaves",
  "handle": "beulah",
  "description": "Beulah IT guys"
}
###
POST http://localhost:4300/users
Content-Type: application/json

{
  "email_address": "nonso@gmail.com",
  "username": "nonso",
  "first_name": "nonso",
  "password": "nonso"
}

###
GET http://localhost:4300/polls/59ffe5ba6e21d02124914b2b
authid: 5a3618879662a518502932c0
###
GET http://localhost:4300/polls/59ffe5e56e21d02124914b2c
authid: 5a3618879662a518502932c0
###
GET http://localhost:4300/users/all
authid: 5a3618879662a518502932c0
###

POST http://localhost:4300/polls/
Content-Type: application/json
AuthID: 5a3618879662a518502932c0

{
  "question": "Who worked more at Beulah?",
  "comment": "A quick poll to know who did more work during IT at Beulah",
  "circle": "5a3618e89662a518502932c1",
  "options": [
    {
      "option": "Ekene",
      "votes":[]
    },
    {
      "option": "Alex",
      "votes":[]
    },
    {
      "option": "Tolu",
      "votes":[]
    },
    {
      "option": "Stephanie",
      "votes":[]
    }
  ]
}

