export const APP_NAME = 'CHAT ANON';
export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const CHANGE_HEADER = 'CHANGE_HEADER'; 
export const RESET_HEADER = 'RESET_HEADER';

export const SETTINGS_SAVED = 'SETTINGS_SAVED';
export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED';

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

export const SET_PAGE = 'SET_PAGE';
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';

export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
