export const APP_NAME = 'CHAT ANON';
export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const CHANGE_HEADER = 'CHANGE_HEADER'; 
export const RESET_HEADER = 'RESET_HEADER';

export const SETTINGS_SAVED = 'SETTINGS_SAVED';
export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED';

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

export const SET_PAGE = 'SET_PAGE';
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const LOGOUT = 'LOGOUT';

export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';



export const CIRCLE_PAGE_LOADED = 'CIRCLE_PAGE_LOADED';
export const CIRCLE_PAGE_UNLOADED = 'CIRCLE_PAGE_UNLOADED';
export const CIRCLE_REQUEST_SENT = 'CIRCLE_REQUEST_SENT';
export const CIRCLE_FELLOW_ADDED = 'CIRCLE_FELLOW_ADDED';
export const CIRCLE_FELLOW_REMOVED = 'CIRCLE_FELLOW_REMOVED';
export const CIRCLE_ADMIN_ADDED = 'CIRCLE_ADMIN_ADDED';
export const CIRCLE_ADMIN_REMOVED = 'CIRCLE_ADMIN_REMOVED';
export const CIRCLE_USERS_PAGE_LOADED = 'CIRCLE_USERS_PAGE_LOADED';
export const CIRCLE_USERS_PAGE_UNLOADED = 'CIRCLE_USERS_PAGE_UNLOADED';
export const CIRCLE_LIST_LOADED = "CIRCLE_LIST_LOADED"; 
export const CIRCLE_LIST_UNLOADED = "CIRCLE_LIST_UNLOADED"; 
export const CIRCLE_DELETED = "CIRCLE_DELETED"; 
export const CIRCLE_CREATED = "CIRCLE_CREATED"; 
export const MY_CIRCLES_REQUESTED = "MY_CIRCLES_REQUESTED"; 
export const CIRCLE_SELECTED = "CIRCLE_SELECTED";



export const POLL_PAGE_LOADED = 'POLL_PAGE_LOADED';
export const POLL_PAGE_UNLOADED = 'POLL_PAGE_UNLOADED';
export const POLL_CREATED = 'POLL_CREATED';
export const POLL_DELETED = 'POLL_DELETED';
export const POLL_FAVORITED = 'POLL_FAVORITED';
export const POLL_UNFAVORITED = 'POLL_UNFAVORITED';
export const POLL_LIST_LOADED = "POLL_LIST_LOADED"; 
export const POLL_LIST_UNLOADED = "POLL_LIST_UNLOADED"; 
export const POLL_VOTED = 'POLL_VOTED';
export const POLL_SELECTED = "POLL_SELECTED";
export const CIRCLE_POLL_PAGE = "CIRCLE_POLL_PAGE";